# Server
server.port=8080
spring.application.name=eventra-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/eventra_db
spring.datasource.username=postgres
spring.datasource.password=LeCrimson@2052
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis (can leave for now, disable if not set up yet)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
app.jwt.secret=eventra-super-secret-key-change-this-in-production-256bits
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=http://localhost:5173

# Flyway (disable until we have our first migration file)
spring.flyway.enabled=false