-- ==========================================
-- COMMUNITIES MODULE SCHEMA
-- ==========================================

-- Community table
CREATE TABLE IF NOT EXISTS community (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(255) NOT NULL,
    description        TEXT,
    cover_image        VARCHAR(255),
    category           VARCHAR(255) NOT NULL,
    created_by_user_id BIGINT,
    member_count       BIGINT NOT NULL DEFAULT 0,
    event_count        BIGINT NOT NULL DEFAULT 0,
    active             BOOLEAN NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Community Member table
CREATE TABLE IF NOT EXISTS community_member (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id BIGINT NOT NULL REFERENCES community(id) ON DELETE CASCADE,
    user_id      BIGINT NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    avatar_url   VARCHAR(255),
    role         VARCHAR(50) NOT NULL DEFAULT 'MEMBER' CHECK (role IN ('MEMBER', 'MODERATOR', 'ADMIN')),
    joined_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_community_member UNIQUE (community_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_community_member_user ON community_member(user_id);

-- Discussion table
CREATE TABLE IF NOT EXISTS discussion (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id  BIGINT NOT NULL REFERENCES community(id) ON DELETE CASCADE,
    title         VARCHAR(255) NOT NULL,
    content       TEXT,
    author_id     BIGINT NOT NULL,
    author_name   VARCHAR(255) NOT NULL,
    author_avatar VARCHAR(255),
    reply_count   INT NOT NULL DEFAULT 0,
    hot           BOOLEAN NOT NULL DEFAULT FALSE,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_discussion_community ON discussion(community_id);
CREATE INDEX IF NOT EXISTS idx_discussion_author    ON discussion(author_id);

-- Discussion Reply table
CREATE TABLE IF NOT EXISTS discussion_reply (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discussion_id BIGINT NOT NULL REFERENCES discussion(id) ON DELETE CASCADE,
    author_id     BIGINT NOT NULL,
    author_name   VARCHAR(255) NOT NULL,
    author_avatar VARCHAR(255),
    content       TEXT NOT NULL,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_discussion_reply_discussion ON discussion_reply(discussion_id);

-- Flagged Content table
CREATE TABLE IF NOT EXISTS flagged_content (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type        VARCHAR(50) NOT NULL CHECK (content_type IN ('DISCUSSION', 'REPLY')),
    content_id          BIGINT NOT NULL,
    community_id        BIGINT,
    author_id           BIGINT NOT NULL,
    author_name         VARCHAR(255) NOT NULL,
    content_preview     TEXT,
    reason              VARCHAR(255) NOT NULL,
    report_count        INT NOT NULL DEFAULT 1,
    status              VARCHAR(50) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REMOVED', 'WARNED')),
    resolved_by_user_id BIGINT,
    resolved_at         TIMESTAMPTZ,
    moderator_note      VARCHAR(255),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ==========================================
-- GAMIFICATION MODULE SCHEMA
-- ==========================================

-- Rewards Profile table
CREATE TABLE IF NOT EXISTS rewards_profile (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL,
    display_name          VARCHAR(255) NOT NULL,
    avatar_url            VARCHAR(255),
    points_balance        BIGINT NOT NULL DEFAULT 0,
    total_points_earned   BIGINT NOT NULL DEFAULT 0,
    total_points_redeemed BIGINT NOT NULL DEFAULT 0,
    totalxp               BIGINT NOT NULL DEFAULT 0,
    current_level         INT NOT NULL DEFAULT 1,
    current_streak        INT NOT NULL DEFAULT 0,
    longest_streak        INT NOT NULL DEFAULT 0,
    last_activity_date    DATE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_rewards_profile_user UNIQUE (user_id)
);

-- Badge table
CREATE TABLE IF NOT EXISTS badge (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL UNIQUE,
    description      TEXT NOT NULL,
    category         VARCHAR(50) NOT NULL CHECK (category IN ('PARTICIPATION', 'ACHIEVEMENT', 'MILESTONE')),
    tier             VARCHAR(50) NOT NULL CHECK (tier IN ('BRONZE', 'SILVER', 'GOLD', 'PLATINUM')),
    unlock_condition VARCHAR(255) NOT NULL,
    xp_bonus         INT NOT NULL,
    icon_url         VARCHAR(255),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- User Badge table
CREATE TABLE IF NOT EXISTS user_badge (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    badge_id    BIGINT NOT NULL REFERENCES badge(id) ON DELETE CASCADE,
    unlocked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_user_badge UNIQUE (user_id, badge_id)
);

CREATE INDEX IF NOT EXISTS idx_user_badge_user ON user_badge(user_id);

-- Points Transaction table
CREATE TABLE IF NOT EXISTS points_transaction (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL,
    xp_amount            BIGINT NOT NULL DEFAULT 0,
    points_amount        BIGINT NOT NULL DEFAULT 0,
    type                 VARCHAR(50) NOT NULL CHECK (type IN ('EARNED', 'SPENT', 'BONUS')),
    reason               VARCHAR(255) NOT NULL,
    reference_id         VARCHAR(255),
    description          VARCHAR(255),
    points_balance_after BIGINT NOT NULL,
    xp_balance_after     BIGINT NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_points_transaction_user ON points_transaction(user_id);

-- Leaderboard table
CREATE TABLE IF NOT EXISTS leaderboard (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    display_name  VARCHAR(255) NOT NULL,
    type          VARCHAR(50) NOT NULL CHECK (type IN ('WEEKLY', 'MONTHLY', 'ALL_TIME')),
    score         BIGINT NOT NULL DEFAULT 0,
    rank_position INT,
    last_updated  TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_leaderboard_user_type UNIQUE (user_id, type)
);
